### ISSUE TITLE
How to import this libs into KMP projects

### ISSUE THREAD

**Issue by arkilis** [SuoxingTech/KMMFoundation#3]
Fantastic project, how do we import the kmm-arch in the kmp project? Thanks!

**Comment by wifi9984** [comment]
Thanks 😄 . First of all these libraries are aimed to the deprecated concept of 'Kotlin Multiplatform Mobile', which means they are only targeted to Android and iOS platforms. If your project implements more than these targets, they are not good choice as well.

For standard KMM project, import `kmm-arch` like this:
```
sourceSets {
    val commonMain by getting {
        /**
         * Add multiplatform dependencies here
         */
        dependencies {
            api("dev.suoxing.kmm:kmm-arch:1.6.0")
        }
    }
```

Important: read `ios/ViewModel` class comment to use ViewModel without memory leak.

**Comment by arkilis** [comment]
Thanks for the prompt reply, I tried with the following, seems still not be able to resolve it.

![image](https://github.com/user-attachments/assets/ff586ce7-399b-4d8a-bf1b-0734261b28cd)

**Comment by wifi9984** [comment]
Sorry for missed that, our libraries are currently published to GitHubPackage, that requires additional configuration, you can checkout latest README for more information.
